name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: openjdk:21-jdk
      options: --user root
    
    steps:
    - uses: actions/checkout@v4.1.4
    - run: |
          chmod +x ./gradlew
          ./gradlew build
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifacts
        path: build/libs/
